name: .NET Core CI

on:
  push:
    branches:
      - main
      - NEX-115-Pipeline
  pull_request:
    branches:
      - main
      - NEX-115-Pipeline

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        project:
          - 'MSP App/App/App.csproj'
          - 'MSP App/API/API.csproj'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.x'

    - name: Restore dependencies
      run: dotnet restore "${{ matrix.project }}"

    - name: Build
      run: dotnet build --no-restore --configuration Release "${{ matrix.project }}"

    - name: Lint and Format
      run: dotnet format --check "${{ matrix.project }}"
