name: Python CI

on:
  push:
    branches:
      - main
      - NEX-115-Pipeline
  pull_request:
    branches:
      - main
      - NEX-115-Pipeline

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.12]
        project:
          - 'Tenant-Client'
          - 'Tenant-Server'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint pytest

    - name: Run tests
      run: |
        cd ${{ matrix.project }}
        pytest test_main.py

    - name: Lint with pylint
      run: |
        cd ${{ matrix.project }}
        pylint $(find . -name "*.py")
