name: Python CI

on:
  push:
    branches:
      - main
      - NEX-115-Pipeline
  pull_request:
    branches:
      - main
      - NEX-115-Pipeline

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.12]
        project:
          - 'Tenant-Client'
          - 'Tenant-Server'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        cd ${{ matrix.project }}
        python -m pip install --upgrade pip
        # Install non-Windows specific packages
        grep -v 'pywin32' requirements.txt | grep -v 'pyuac' | grep -v 'pywin32-ctypes' | python -m pip install -r /dev/stdin

    - name: List installed packages
      run: |
        cd ${{ matrix.project }}
        python -m pip list

    - name: Run tests
      run: |
        cd ${{ matrix.project }}
        pytest || true
